[project]
name = 'CryptoRewards'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.ChallengeSystem]
path = 'contracts/ChallengeSystem.clar'
clarity_version = 3
epoch = 3.1

[contracts.CryptoRewards]
path = 'contracts/CryptoRewards.clar'
clarity_version = 3
epoch = 3.1

[contracts.ChallengePool]
path = 'contracts/ChallengePool.clar'
clarity_version = 3
epoch = 3.1 

[contracts.RewardMarketplace]
path = 'contracts/RewardMarketplace.clar'
clarity_version = 3
epoch = 3.1 

[contracts.MerchantDashboard]
path = 'contracts/MerchantDashboard.clar'
clarity_version = 3
epoch = 3.1

[contracts.RewardsAnalytics]
path = 'contracts/RewardsAnalytics.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
